# Generated by Django 4.1.4 on 2022-12-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
